name: Matrix Example
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        A: [A1, A2]
        B: [B1, B2, B3]
    steps:
    - name: Step 1
      run: echo ${{ matrix.A }} ${{ matrix.B }}